### ISSUE TITLE
preferences file can't be loaded from old version

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/termonad#189]
It appears there is a problem loading the preferences file if it is missing fields.

Here is what my preferences file looks like:

```console
$ cat ~/.config/termonad/termonad.yaml 
# DO NOT EDIT THIS FILE BY HAND!
#
# This file is generated automatically by the Preferences dialog
# in Termonad.  Please open the Preferences dialog if you wish to
# modify this file.
#
# The settings in this file will be ignored if you have a
# termonad.hs file in this same directory.

confirmExit: true
showTabBar: ShowTabBarAlways
showScrollbar: ShowScrollbarAlways
wordCharExceptions: '-#%&+,./=?@\_~·:'
showMenu: true
cursorBlinkMode: CursorBlinkModeOn
scrollbackLen: 20000
fontConfig:
  fontFamily: DejaVu Sans Mono
  fontSize:
    tag: FontSizePoints
    contents: 13
```

This is from an old version of Termonad.  You can see that it is missing the `boldIsBright` option added in https://github.com/cdepillabout/termonad/issues/176.

When I try to run Termonad with this preferences file, I get the following error:

```
Error parsing file /home/user/.config/termonad/termonad.yaml
Aeson exception:
Error in $: parsing Termonad.Types.ConfigOptions(ConfigOptions) failed, key "boldIsBright" not found
```

If I delete `~/.config/termonad/termonad.yaml`, restart Termonad, open the Preferences dialog, and press `Okay`, Termonad recreates the preferences file with `boldIsBright` set correctly:

```yaml
# DO NOT EDIT THIS FILE BY HAND!
#
# This file is generated automatically by the Preferences dialog
# in Termonad.  Please open the Preferences dialog if you wish to
# modify this file.
#
# The settings in this file will be ignored if you have a
# termonad.hs file in this same directory.

confirmExit: true
showTabBar: ShowTabBarAlways
boldIsBright: false
showScrollbar: ShowScrollbarAlways
wordCharExceptions: '-#%&+,./=?@\_~·:'
showMenu: true
cursorBlinkMode: CursorBlinkModeOn
scrollbackLen: 20000
fontConfig:
  fontFamily: DejaVu Sans Mono
  fontSize:
    tag: FontSizePoints
    contents: 13
```

--------------------------------------------------------------------------

It would be nice for Termonad to not throw an error when parsing a configuration file that is missing some fields.  These fields should be defaulted to whatever their default value is.

This is the function that reads from the preferences file:

https://github.com/cdepillabout/termonad/blob/dd6b6438727aae5f7f6f9e9bc9d8b98e5b95e550/src/Termonad/PreferencesFile.hs#L29-L48

This probably needs to be relaxed to not fail if some fields are missing.
